# -*- coding: utf-8 -*-
"""join.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V4BLv4DhnnSfR-h41XZ_1XwgWq43EqUc
"""

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd

sonar_issues=pd.read_csv('/content/drive/MyDrive/TAED2/sonar_issues_fixed.csv')
sonar_issues=sonar_issues.rename(columns={"CREATION_ANALYSIS_KEY":"key"})
sonar_issues

sonar_measures=pd.read_csv('/content/drive/MyDrive/TAED2/new_sonar_measures.csv')
sonar_measures=sonar_measures.rename(columns={"analysis_key":"key"})
sonar_measures

sonar_analysis=pd.read_csv('/content/drive/MyDrive/TAED2/The-Technical-Debt-Dataset-CSV/SONAR_ANALYSIS.csv')
sonar_analysis

Sonar = pd.merge(sonar_issues, sonar_measures, on='key', how='inner')
Sonar

Sonar.columns

Sonar.to_csv('/content/drive/MyDrive/TAED2/sonar.csv',index = False, header=True)